'use client'

import { useMemo, useState } from 'react'
import { Search, Download, Plus, MapPin, Upload, CalendarDays, CheckCircle2, AlertTriangle, ArrowRight, FileText } from 'lucide-react'
import { alerts, canPerform, children, inventory, vaccines, type UserRole } from '@/lib/echims-data'
import { useAuth } from '@/components/auth/auth-provider'

const titles = ['Child Profiling', 'Vaccination', 'Nutritional Assessment', 'Supplementation', 'Inventory', 'Alerts', 'Reports', 'User Management', 'Settings', 'Health Activities']

export function ModulePage({ slug }: { slug: string[] }) {
  const title = slug.map((part) => part.replace(/-/g, ' ')).join(': ').replace(/\b\w/g, (letter) => letter.toUpperCase())
  const root = slug[0]
  const { user } = useAuth()
  const role = (user?.role ?? 'Administrator') as UserRole
  const moduleName = ({ 'child-profiling': 'Child Profiling', vaccination: 'Vaccination', 'nutritional-assessment': 'Nutritional Assessment', supplementation: 'Supplementation', inventory: 'Inventory', reports: 'Reports', 'health-activities': 'Health Activities' } as Record<string, string>)[root] ?? title
  const canCreate = canPerform(role, moduleName, 'create')
  const canExport = canPerform(role, moduleName, 'export')
  const [query, setQuery] = useState('')
  const [showForm, setShowForm] = useState(false)
  const rows = useMemo(() => {
    if (root === 'child-profiling') return children.filter((child) => child.name.toLowerCase().includes(query.toLowerCase()))
    if (root === 'vaccination') return vaccines.filter((vaccine) => vaccine.child.toLowerCase().includes(query.toLowerCase()))
    if (root === 'inventory') return inventory.filter((item) => item.item.toLowerCase().includes(query.toLowerCase()))
    return []
  }, [query, root])

  if (root === 'user-management') return <UserManagement currentUser={user} onCreate={() => setShowForm(true)} showForm={showForm} onClose={() => setShowForm(false)} />

  if (root === 'alerts') return <section className="flex flex-col gap-6"><Header title="Alerts" description="Review system notifications that need attention." action="Mark all as read" /><div className="grid gap-4">{alerts.map((alert) => <article key={alert.title} className="flex items-start gap-4 rounded-xl border border-[#E5E7EB] bg-white p-5 shadow-sm"><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-[#CAF0F8] text-[#0077B6]"><AlertTriangle size={19} /></div><div className="flex-1"><h3 className="font-semibold text-[#03045E]">{alert.title}</h3><p className="mt-1 text-sm text-[#6B7280]">{alert.detail}</p></div><span className="rounded-full bg-[#FFF7ED] px-3 py-1 text-xs font-semibold text-[#C2410C]">Action needed</span></article>)}</div></section>

  if (root === 'reports') return <section className="flex flex-col gap-6"><Header title="Reports" description="Generate and export health program reports." action={canCreate ? 'Generate report' : 'View reports'} onAction={canCreate ? () => setShowForm(true) : undefined} /><div className="grid gap-4 md:grid-cols-3">{['Child Health Summary', 'Vaccination Coverage', 'Nutrition Risk Register', 'Inventory Movement', 'Supplementation Report', 'Activity Performance'].map((report) => <button key={report} onClick={() => setShowForm(true)} className="flex items-center gap-4 rounded-xl border border-[#E5E7EB] bg-white p-5 text-left shadow-sm transition hover:border-[#90E0EF]"><div className="flex size-10 items-center justify-center rounded-lg bg-[#E0F5FA] text-[#0077B6]"><FileText size={19} /></div><span className="font-semibold text-[#03045E]">{report}</span></button>)}</div>{showForm && <SimpleForm title="Generate report" onClose={() => setShowForm(false)} />}</section>

  if (root === 'health-activities' || root === 'vaccination' && slug[1] === 'calendar') return <CalendarView title={root === 'health-activities' ? 'Health Activities' : 'Vaccination Calendar'} />

  const isTable = rows.length > 0
  return <section className="flex flex-col gap-6"><Header title={title} description={descriptionFor(root)} action={canCreate ? (root === 'child-profiling' ? 'Upload Masterlist' : 'Add new record') : 'View records'} onAction={canCreate ? () => setShowForm(true) : undefined} /><div className="flex flex-col gap-4 rounded-xl border border-[#E5E7EB] bg-white p-4 shadow-sm md:flex-row md:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9CA3AF]" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${root === 'inventory' ? 'items' : 'records'}...`} className="w-full rounded-lg border border-[#E5E7EB] py-2.5 pl-10 pr-3 text-sm outline-none focus:border-[#0077B6]" /></div><select aria-label="Filter by barangay" className="rounded-lg border border-[#E5E7EB] bg-white px-3 py-2.5 text-sm text-[#6B7280] outline-none focus:border-[#0077B6]"><option>All barangays</option><option>San Isidro</option><option>Poblacion</option><option>Mabini</option><option>San Roque</option></select>{canExport && <button className="flex items-center justify-center gap-2 rounded-lg border border-[#0077B6] px-4 py-2.5 text-sm font-semibold text-[#0077B6]"><Download size={16} />Export CSV</button>}</div>{isTable ? <DataTable root={root} rows={rows} /> : <EmptyModule title={title} onAction={() => canCreate && setShowForm(true)} />}{showForm && canCreate && <SimpleForm title={root === 'child-profiling' ? 'Add child profile' : `Add ${title.toLowerCase()} record`} onClose={() => setShowForm(false)} />}</section>
}

function UserManagement({ currentUser, onCreate, showForm, onClose }: { currentUser: { fullName: string; username: string; email: string; role: UserRole; employeeId: string } | null; onCreate: () => void; showForm: boolean; onClose: () => void }) {
  return <section className="flex flex-col gap-6"><Header title="User Management" description="Create accounts, assign roles, and manage account status." action="Create user" onAction={onCreate} /><div className="overflow-hidden rounded-xl border border-[#E5E7EB] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#F8FAFC] text-xs uppercase tracking-wide text-[#6B7280]"><tr>{['Full Name', 'Username', 'Email', 'Role', 'Employee ID', 'Status', 'Action'].map((head) => <th key={head} className="px-5 py-4 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-[#E5E7EB]">{currentUser && <tr><td className="px-5 py-4 font-semibold text-[#03045E]">{currentUser.fullName}</td><td className="px-5 py-4 text-[#6B7280]">{currentUser.username}</td><td className="px-5 py-4 text-[#6B7280]">{currentUser.email}</td><td className="px-5 py-4"><span className="rounded-full bg-[#E0F5FA] px-2.5 py-1 text-xs font-semibold text-[#0077B6]">{currentUser.role}</span></td><td className="px-5 py-4 text-[#6B7280]">{currentUser.employeeId || '—'}</td><td className="px-5 py-4"><Badge label="Active" /></td><td className="px-5 py-4"><button className="font-semibold text-[#0077B6]">View / Edit</button></td></tr>}</tbody></table></div></div>{showForm && <UserForm onClose={onClose} />}</section>
}

function UserForm({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#03045E]/30 p-4"><div className="max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-[#03045E]">Create user account</h2><button onClick={onClose} className="text-2xl text-[#6B7280]">×</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{['Full Name', 'Username', 'Email', 'Contact Number', 'Employee ID', 'License Number', 'Barangay Assignment'].map((label) => <label key={label} className="grid gap-1.5 text-sm font-medium text-[#03045E]">{label}<input className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal outline-none focus:border-[#0077B6]" /></label>)}<label className="grid gap-1.5 text-sm font-medium text-[#03045E]">Role<select className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal"><option>Administrator</option><option>Public Health Nurse</option><option>Barangay Health Worker</option><option>Rural Health Midwife</option><option>Barangay Nutrition Scholar</option></select></label><label className="grid gap-1.5 text-sm font-medium text-[#03045E]">Account Status<select className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal"><option>Active</option><option>Inactive</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="rounded-lg border border-[#E5E7EB] px-4 py-2 text-sm font-semibold text-[#6B7280]">Cancel</button><button onClick={onClose} className="rounded-lg bg-[#0077B6] px-4 py-2 text-sm font-semibold text-white">Save account</button></div></div></div> }

function Header({ title, description, action, onAction }: { title: string; description: string; action: string; onAction?: () => void }) { return <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-[#0077B6]">eCHIMS Workspace</p><h1 className="mt-1 text-3xl font-bold text-[#03045E]">{title}</h1><p className="mt-2 text-sm text-[#6B7280]">{description}</p></div><button onClick={onAction} className="flex items-center justify-center gap-2 rounded-lg bg-[#0077B6] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#005F8F]"><Plus size={17} />{action}</button></header> }
function DataTable({ root, rows }: { root: string; rows: any[] }) { return <div className="overflow-hidden rounded-xl border border-[#E5E7EB] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#F8FAFC] text-xs uppercase tracking-wide text-[#6B7280]"><tr>{(root === 'child-profiling' ? ['Child ID', 'Name', 'Age', 'Barangay', 'Status', 'Action'] : root === 'vaccination' ? ['Child', 'Vaccine', 'Dose', 'Date', 'Status', 'Action'] : ['Item', 'Barangay', 'On Hand', 'Reorder Level', 'Status', 'Action']).map((head) => <th key={head} className="px-5 py-4 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((row, index) => <tr key={index} className="hover:bg-[#F8FAFC]">{root === 'child-profiling' ? <><td className="px-5 py-4 font-medium text-[#0077B6]">{row.id}</td><td className="px-5 py-4 font-semibold text-[#03045E]">{row.name}</td><td className="px-5 py-4 text-[#6B7280]">{row.age}</td><td className="px-5 py-4 text-[#6B7280]">{row.barangay}</td><td className="px-5 py-4"><Badge label={row.status} /></td></> : root === 'vaccination' ? <><td className="px-5 py-4 font-semibold text-[#03045E]">{row.child}</td><td className="px-5 py-4 text-[#6B7280]">{row.vaccine}</td><td className="px-5 py-4 text-[#6B7280]">{row.dose}</td><td className="px-5 py-4 text-[#6B7280]">{row.date}</td><td className="px-5 py-4"><Badge label={row.status} /></td></> : <><td className="px-5 py-4 font-semibold text-[#03045E]">{row.item}</td><td className="px-5 py-4 text-[#6B7280]">{row.barangay}</td><td className="px-5 py-4 font-semibold text-[#03045E]">{row.onHand}</td><td className="px-5 py-4 text-[#6B7280]">{row.reorder}</td><td className="px-5 py-4"><Badge label={row.status} /></td></>}<td className="px-5 py-4"><button className="font-semibold text-[#0077B6]">View <ArrowRight className="ml-1 inline" size={14} /></button></td></tr>)}</tbody></table></div></div> }
function Badge({ label }: { label: string }) { const good = ['Done', 'Normal', 'Active', 'Under Monitoring'].includes(label); return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${good ? 'bg-[#E8F7EE] text-[#16803C]' : label === 'At Risk' || label === 'Missed' || label === 'Out of Stock' ? 'bg-[#FEECEC] text-[#B42318]' : 'bg-[#FFF7ED] text-[#C2410C]'}`}>{label}</span> }
function EmptyModule({ title, onAction }: { title: string; onAction: () => void }) { return <div className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-dashed border-[#BDEAF5] bg-white p-8 text-center"><div className="flex size-12 items-center justify-center rounded-full bg-[#E0F5FA] text-[#0077B6]"><Plus size={20} /></div><h2 className="mt-4 font-semibold text-[#03045E]">No {title.toLowerCase()} records yet</h2><p className="mt-1 max-w-md text-sm text-[#6B7280]">Create a record to start tracking this part of the community health workflow.</p><button onClick={onAction} className="mt-4 rounded-lg bg-[#0077B6] px-4 py-2 text-sm font-semibold text-white">Create record</button></div> }
function SimpleForm({ title, onClose }: { title: string; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-[#03045E]/30 p-4"><div className="max-h-[calc(100vh-2rem)] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-[#03045E]">{title}</h2><button onClick={onClose} className="text-2xl text-[#6B7280]" aria-label="Close form">×</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{['Child or item name', 'Date', 'Barangay', 'Status'].map((label) => <label key={label} className="grid gap-1.5 text-sm font-medium text-[#03045E]">{label}{label === 'Date' ? <input type="date" className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal outline-none focus:border-[#0077B6]" /> : label === 'Barangay' ? <select className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal outline-none focus:border-[#0077B6]"><option>Select barangay</option><option>San Isidro</option><option>Poblacion</option><option>Mabini</option><option>San Roque</option></select> : label === 'Status' ? <select className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal outline-none focus:border-[#0077B6]"><option>Active</option><option>Pending</option><option>Completed</option><option>At Risk</option></select> : <input className="rounded-lg border border-[#E5E7EB] px-3 py-2.5 font-normal outline-none focus:border-[#0077B6]" placeholder={`Enter ${label.toLowerCase()}`} />}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="rounded-lg border border-[#E5E7EB] px-4 py-2 text-sm font-semibold text-[#6B7280]">Cancel</button><button onClick={onClose} className="rounded-lg bg-[#0077B6] px-4 py-2 text-sm font-semibold text-white">Save record</button></div></div></div> }
function CalendarView({ title }: { title: string }) { return <section className="flex flex-col gap-4"><Header title={title} description="Plan, review, and follow up on community health activities." action="Create schedule" /><div className="grid gap-3 md:grid-cols-7">{['Mon 15', 'Tue 16', 'Wed 17', 'Thu 18', 'Fri 19', 'Sat 20', 'Sun 21'].map((day, index) => <div key={day} className="min-h-36 rounded-xl border border-[#E5E7EB] bg-white p-2.5 shadow-sm"><p className="text-xs font-bold uppercase text-[#6B7280]">{day}</p>{index < 5 && <div className="mt-3 rounded-lg bg-[#E0F5FA] p-2.5 text-xs font-semibold text-[#0077B6]"><CalendarDays size={14} className="mb-1.5" />{index % 2 ? 'Child Profiling' : 'Vaccination'}<p className="mt-1 font-normal text-[#6B7280]">09:00 AM · San Isidro</p></div>}</div>)}</div><div className="rounded-xl border border-[#E5E7EB] bg-white p-4 shadow-sm"><h2 className="font-bold text-[#03045E]">Schedule approval workflow</h2><div className="mt-3 flex flex-wrap items-center gap-2 text-sm">{['Pending Approval', 'Approved', 'Scheduled', 'In Progress', 'Completed'].map((step, index) => <div key={step} className="flex items-center gap-2"><span className={`rounded-full px-3 py-1.5 font-semibold ${index === 0 ? 'bg-[#FFF7ED] text-[#C2410C]' : 'bg-[#E8F7EE] text-[#16803C]'}`}>{step}</span>{index < 4 && <ArrowRight size={14} className="text-[#9CA3AF]" />}</div>)}</div></div></section> }
function descriptionFor(root: string) { return ({ 'child-profiling': 'Manage child records, monitoring status, and community profiles.', vaccination: 'Track immunization records, due doses, and follow-up schedules.', 'nutritional-assessment': 'Record measurements and monitor children requiring nutrition support.', supplementation: 'Track recommendations, distribution, and supplementation history.', inventory: 'Monitor stock levels, allocations, and supply movements.', 'user-management': 'Manage eCHIMS users, roles, and access permissions.', settings: 'Manage your profile, organization details, and account preferences.' } as Record<string, string>)[root] || 'Manage this eCHIMS workflow from one workspace.' }
